export { default as Header } from './Header'
export { default as Title } from './Title'
export { default as About } from './About'
export { default as Resume } from './Resume'
export { default as Works } from './Works'
export { default as Footer } from './Footer'
